def main():
	print('hello')
	players = {}

	for k,v in toons.items():
		if v not in players:
			players[v] = [k]
		else:
			players[v].append(k)


	for p,t in players.items():
		x = '['
		for name in t:
			x = x + name + ','
		x = x + ']'
		print('\''+p+'\':'+x+',')


toons = {
	'Contact Hologram':'',
	'UnregScrim':'',
	'Sklarped':'',
	'JC Pose':'hp',
	'ghostmaster':'xhiggy',
	'Datura':'vertigo blue',
	'Lustful':'syn',
	'ILLUMlNATl':'rick james',
	'rko':'ricko',
	'M3z':'m3z',
	'Zhu Que':'phoenix',
	'Kerridwen':'liberty',
	'Reefer':'bangbangdoof',
	'Up Dogger':'dogger',
	'Mallex':'mallex',
	'Botulinum Toxin':'fire wire',
	'Apollo CAWWWeed':'larry lobster',
	'Jetpack Wolfman':'xhiggy',
	'Daydream Believer':'tempty',
	'Absquatulate Early':'dexington',
	'Geuze':'bangbangdoof',
	'Cruel Existence':'seagate',
	'ouch':'xhiggy',
	'xray5':'haunt',
	'Professor Grumpy':'march',
	'tourniquet':'xhiggy',
	'Pliny The Elder':'bangbangdoof',
	'electric lettuce':'haunt',
	'Nyx Spectra':'liberty',
	'WannabeBlaster':'',
	'La Escala Perdido':'kyle',
	'Quasimoto':'mad villain',
	'Peanut':'peanut',
	'Kencian X':'kencian',
	'GfNotGf':'paul',
	'JemHadar 1st':'maximum',
	'Flaming Compost':'spec',
	'Apocalypticism':'liberty',
	'Americas Angel':'americas angel',
	'Novatix':'sarr',
	'Firetwist':'firetwist',
	'Los Angeles':'cubano',
	'Beezer':'bangbangdoof',
	'Frozentreatzz':'',
	'mosskin':'xhiggy',
	'Washed':'hells',
	'spicyboy95':'silit',
	'Quadrilateral':'mallex',
	'hellp':'hp',
	'Idolator':'z',
	'Firehawk Maximum1':'maximum',
	'Over Dramatic':'avid',
	'SiphSiph':'siph',
	'Mr Meaner':'spec',
	'mogy patchouli':'mogy',
	'Maximum Scourge':'maximum',
	'Drunk Love':'drunk love',
	'Tetrahedrona':'diotrophes',
	'Dogger':'dogger',
	'Jhaunt':'haunt',
	'Miffed Off':'dexington',
	'Hereditary':'kyle',
	'In Bloom':'macskull',
	'Call Him Mommy':'hot heals',
	'Flying Battery':'silent method',
	'Peaks':'barrier',
	'John Biazzi':'haunt',
	'Viridious':'liberty',
	'Count Dooky':'haunt',
	'Call Her Daddy':'poned',
	'Maverick Hunter X2':'maverick',
	'Crusty Sock':'acid',
	'Roasted Taters':'seductive',
	'Pot':'bangbangdoof',
	'Wilson Wonkerson':'larry lobster',
	'Kencian Z':'kencian',
	'hellaween':'xhiggy',
	'Firehawk Maximum':'maximum',
	'Siphs Canceled':'siph',
	'Get Well Soon':'hot heals',
	'Blaziernoed':'xhiggy', # some hp
	'Bae for the Night':'poned',
	'California Wildfire':'macskull',
	'Mogy Mogy':'mogy',
	'Mescaline':'barrier',
	'Neurotrauma':'liberty',
	'Mexi':'bangbangdoof',
	'Generic PvP':'amra',
	'Quas':'mad villain',
	'Next Target':'',
	'MF Antec':'antec',
	'Huskar':'maverick',
	'Shinobi Test':'',
	'Lyfe4orce':'conro',
	'Space God':'mono',
	'Burnn':'',
	'Wreck':'wreck',
	'Chika Chika':'',
	'Healing Balloon':'jicco',
	'Dr. Funkenhot':'hot heals',
	'4Hundred Degreez3':'control',
	'Were All Mad Here':'macskull',
	'Healing Balloon1':'jicco',
	'Arcadea':'void',
	'Doomstark':'mad villain',
	'av.x':'avprince',
	'Tempting Fate':'tempty',
	'DBZ':'dbz',
	'Sea Slug':'xhiggy',
	'El Beamo Laserano':'',
	'Maverick Hunter X4':'maverick',
	'Naturopathy':'hot heals',
	'Inebriated':'amra',
	'Beam Weaver':'dexington',
	'Kill Potential':'xhiggy',
	'March Redux':'march',
	'No Endorphins':'kyle',
	'Comfortably Numb':'liberty',
	'King Geedorah':'mad villain',
	'some barrir':'barrier',
	'Apollo-':'maximum',
	'NumiLeaf':'numi',
	'Bobingy':'',
	'Down Dogger':'dogger',
	'dragonzoid':'xhiggy',
	'drunken hot':'hot heals',
	'Sklarped 2.0':'',
	'Wildfire Kara':'kara',
	'El Bandido':'cubano',
	'Garbagio':'sarr',
	'Entanglement Janie':'janie',
	'Fernfire':'9lives',
	'appendogtomy':'*',
	'Kencianite':'kencian',
	'Pnd':'poned',
	'White T Poison':'silit',
	'Average Friend':'hells',
	'Delectington':'dexington',
	'Indecent':'z',
	'March Fire':'march',
	'Blazing Doyler':'doyler',
	'Iyanla':'hot heals',
	'NobGoblin':'acid',
	'Arc Impulse':'silent method',
	'March':'march',
	'Doom Reverb':'silent method',
	'Eschatologist':'barrier',
	'Large Kahuna':'charlie',
	'Burger':'dogger',
	'Mazus Illusioneer':'mazus',
	'Naturdays':'bangbangdoof',
	'some natural':'mjb',
	'Lamborgni':'haunt',
	'dan jr':'smallz',
	'Give a man a Poona':'',
	'Miami':'ricko',
	'Airlia':'void',
	'upsetti spaghetti':'silit',
	'Darth Dogger':'dogger',
	'Colonel Wun':'mallex',
	'Rock Hard Lobster':'larry lobster',
	'Flowervillain':'mad villain',
	'Hot Girl Siph':'siph',
	'Iceberg Lettuce':'z',
	'Python Blue':'silit',
	'sanitation':'xhiggy',
	'Moolax':'mallex',
	'Fear Index':'m3z',
	'Big Dogger':'dogger',
	'Gnocchi':'bangbangdoof',
	'Bzzzzzzzzzzzt':'mallex',
	'Thumbelina Janie':'janie',
	'Xylophonics':'astro',
	'Pacemaker':'xhiggy',
	#'Cookes Electronics Employee':'',
	'some entropy':'mjb',
	'Bysmiel':'dogger',
	'wrektum':'wreck',
	'piste':'xhiggy',
	'Aaron With An E':'seductive',
	'Raedawn':'raedawn',
	'Winter Warrior':'maximum',
	'Ravenfrost':'liberty',
	'some mood killer':'mjb',
	'big mama EATS':'silit',
	'Mallxice':'mallex',
	'Chili Dogger':'dogger',
	'Echo The Envoy':'echo wave',
	'1987':'',
	'Pyro Mania':'',
	'Cosmedic':'cosine',
	'Target Me?':'exiled',
	'Wheres Ye Booty':'amra',
	'Franklin S Tower':'blue jay',
	'Fuse':'xhiggy',
	'spooky jim':'smallz',
	'Deadweight':'barrier',
	'Choosen One':'charlie',
	'ponedhub':'hot heals',
	'Juicy Bits':'bangbangdoof',
	'tomato johnsone':'silit',
	'Boo Bees':'wreck',
	'Die Another Day Kara':'kara',
	'Faceless Void':'maverick',
	'DeBeZee':'dbz',
	'Arctic Mariner':'',
	'Premature Evacuation':'',
	#'Night Widow':'',
	'Ryly Fast':'ryry',
	'peraginie alfredo':'silit',
	'Phantom Grip':'sarr',
	'Wonder Womban':'womb',
	'some glock':'mjb',
	'Darkencian':'kencian',
	#'Gun Drone':'',
	'Orval':'bangbangdoof',
	'Masque':'masque',
	'o Y O':'womb',
	'Ellington':'ricko',
	'smol arms fire':'void',
	'Sus Kencian':'kencian',
	'wOYOm':'womb',
	'FML':'masque',
	'Metal Dragon':'mad villain',
	'Beef Dipped':'bangbangdoof',
	'Caster Shell XIV':'mazus',
	'geistmeister':'xhiggy',
	#'Umbra Beast':'',
	'Americas AngeI':'americas angel',
	'HzPiggy':'hp',
	'mogy':'mogy',
	'biazzi':'haunt',
	'space camp':'xhiggy',
	'Cold Heals':'hells',
	#'Jack Frost':'',
	'Caera':'void',
	'Unholy Syn':'syn',
	'Nispy':'',
	'wmb.':'womb',
	'Can we play Deceit?':'',
	'just evade plz':'hells',
	'Soul Penguin':'exit',
	'lig8tnig':'haunt',
	'wmb':'womb',
	'Deaths Blaster':'deathtrip',
	'QBNA':'cubano',
	'i tRow iCe b0Ltz':'',
	'iNc Oroboros':'eclipse',
	'Burnn Toxin':'',
	'Hooonnnn Yeeaaaa':'exiled',
	'DadNotDad':'paul',
	'Dieharder':'reib',
	'A Stubborn Princess':'',
	'Wrecktum':'wreck',
	'Dark Humor.':'dark humor',
	'Deaths Other':'deathtrip',
	'Blazed Haze':'',
	'Disdain-':'maximum',
	'thirsttrap':'wicked space',
	'Chaotic Beam':'',
	'Helium Balloon':'jicco',
	'Not Haze':'',
	'Drainos':'mad villain',
	'BFNotBF':'paul',
	'Final Elements':'',
	'Balance Beam':'bangbangdoof',
	'Iord jesus':'bangbangdoof',
	'Bushs Baked Beams':'',
	'HyperNormalisation':'seagate',
	'fissile':'xhiggy',
	'South Central Druid':'liberty',
	'Vipera':'m3z',
	#'Punk':'',
	#'Soldier':'',
	#'Enforcers':'',
	#'Arsonist':'',
	#'Medic':'',
	'found my super suit':'larry lobster',
	'Premiere':'liberty',
	'Blow':'bangbangdoof',
	'No ProblIama':'womb',
	#'Spec Ops':'',
	'Hell Oh':'antec',
	'ClinkzBones':'maverick',
	'Post Apocalyptica':'liberty',
	'mona lisa rice':'silit',
	'Anything?':'liberty',
	'MalIex':'mallex',
	'Kabeam Abdul Jabbar':'silit',
	'Hell Pigeon':'z',
	'Phosphorescences':'kyle',
	'Beams And CornBread':'seductive',
	'String Beams':'bangbangdoof',
	'Wawy Wobster':'larry lobster',
	#'Oil Slick':'',
	'Metal Visage':'mad villain',
	'Kinuminom':'numi',
	'Beetlebeam':'9lives',
	'Mallexplore':'mallex',
	'BhB LF PnP':'paul',
	'butterface':'haunt',
	'Big Tuna Dynamo':'kyle',
	'KencianX':'kencian',
	'BeamNotBeam':'paul',
	'Io-oI':'womb',
	'P O S T L E F T':'m3z',
	'Pscuse Me':'',
	'Whorl':'xhiggy',
	'KB Bot':'',
	'Brain Scythe':'heksenketel',
	'Ban Gogh':'',
	'DUMPSTER DUMP':'',
	'Gather at spawn':'',
	'Press ALT F4':'',
	'Hot Rocket':'gunrock',
	'Bad Leftovers':'heksenketel',
	'deceit? pls':'',
	'Lesotho':'hinden',
	'Cireaus':'ciro',
	'Fire McFighter':'gunrock',
	'Derpin':'',
	'SmallzBannedMe':'',
	'Pumped Peanut':'',
	'old man hans':'',
	'4Hundred Degreez':'control',
	'Meg Thee Stallion':'hot heals',
	'Disrespectful AF':'masque',
	'Rival Dealer':'m3z',
	'Huma':'phoenix',
	'Raunchy':'hot heals',
	'Anzu':'phoenix',
	'Elite Jupitarian':'liberty',
	'Creepr':'',
	'Excogitate':'dexington',
	'Beaminom':'numi',
	'Helios-':'maximum',
	'Joules Wattson':'sarr',
	'DoubleBeam':'doubleburt',
	'Psychedelics':'kyle',
	'Blood Boiler.':'dark humor',
	'MiSSTAKEN':'misstaken',
	'Cryton-':'maximum',
	'Livin The Beam':'',
	'My New Beamer':'',
	'Opt1mo':'rick james',
	'Such Black Light':'ace hunter',
	'riq':'ricko',
	'Sarr Fire':'sarr',
	'VGS':'march',
	'great friend':'xhiggy',
	'Crepe Caper':'dexington',
	'ChikaChika':'',
	'Fyre Ash':'',
	'5am I Am':'astro',
	'wrekk':'wreck',
	'Tempty locks up dogs':'',
	'Rowdy669':'rowdy',
	'Mordesh':'tanzie',
	'Sobriety':'hot heals',
	'Soy Sauce AF':'',
	'Hi-FructosePornSyrup':'womb',
	'oY0':'womb',
	'Domestic Goddess':'silit',
	'Mallexecution':'mallex',
	'Ra Anubis Ka-':'spiner',
	'drink responsibly':'hot heals',
	'exciplex':'xhiggy',
	'Pterodactyl':'dexington',
	'Ryghteous':'ryry',
	'Doc Hollandaise':'',
	'bigJustin400':'',
	#'Winter Wolf':'',
	'camp thief':'xhiggy',
	'MonoBugsnax':'mono',
	'Repercussion':'hot heals',
	'Gascon':'',
	'Sun-God':'condro',
	'All The Endorphins':'kyle',
	'wrek':'wreck',
	'QBNO':'cubano',
	'Cyanide N. SMOLness':'kara',
	'Balloon Knot':'ace hunter',
	'Twisted Assistant':'acid',
	'pandemic mike':'silit',
	'potato mike':'silit',
	'Solael':'liberty',
	'Post February':'march',
	'Red.X':'',
	'Mogy mogy':'mogy',
	'Bushwhack':'dogger',
	'Online':'hp',
	'PsychStar':'larouse',
	'Haxan Cloak':'m3z',
	'A s t r o':'astro',
	'ra anubis ka':'xhiggy',
	'Nefarious Artic':'artic',
	'Noidankattila':'heksenketel',
	'SeismicCiro':'ciro',
	'Magma':'',
	'Stasis Star':'deathvirus',
	'CM Plz':'gunrock',
	'Wave Turtle':'exit',
	'BottomoftheBarrel':'',
	'Despacito':'',
	'Lord Jesus':'bangbangdoof',
	'Ravenfrosty':'liberty',
	'Revelation':'m3z',
	'Mallex undercover':'mallex',
	'What in Tarnation':'kyle',
	'Prysmatica':'liberty',
	'dotcom':'silit',
	'Pressing Buttons':'dexington',
	'Sadge':'mallex',
	'Ghoulish':'z',
	'Refactor':'vinnie',
	'damsel in distress':'hot heals',
	'jacuzzi':'silit',
	'lootpack woofman':'xhiggy',
	'Vanishing Point':'m3z',
	'Cannon.':'reib',
	'Over-Charged1':'',
	'Clinix':'seductive',
	'2020':'ricko',
	'catJAM':'mallex',
	'Sweaty':'bp',
	'Seizoen Bretta':'bangbangdoof',
	'0Yo':'womb',
	'Same Dew':'trey',
	'Four20':'control',
	'lo-ol':'womb',
	'Tiny Dogger':'dogger',
	'Teenie Weenie':'dogger',
	'Kisthmus Thime':'amra',
	'Cancer Enhancer':'womb',
	'Artic Warfare':'artic',
	'fartmaster':'',
	'Cirous':'ciro',
	'SpicyCiro':'ciro',
	'ohmbre':'haunt',
	'MEDICATED':'rick james',
	'Palau':'hinden',
	'some target':'mjb',
	'EarthFire Dom AF':'',
	'Dark Humour.':'dark humor',
	'Wrekk':'wrek',
	'Blackbody':'mad villain',
	'BeamingDown-DaBlock':'condro',
	'Not MV':'',
	'WashedUpStar':'larouse',
	'A L L C A P S':'mad villain',
	'Plup':'mallex',
	'Beam Me Up Peanut':'peanut',
	'Wreckz':'wreck',
	'DoubleBurt':'doubleburt',
	'RiRi':'ryry',
	'Bzzzzzzzzt':'mallex',
	#'Lion':'',
	'Aiden-':'aiden',
	'Hoarfrosty':'spiner',
	'TheMalice':'mallice',
	'Not Emp':'jicco',
	#'Toxic Tarantula':'',
	'Darkrain':'bangbangdoof',
	#'Grave Knight':'',
	'Outergalactic':'liberty',
	'Procy Balboa':'masque',
	'Scratch N Sniff':'maj',
	'th0tless':'smallz',
	'Maximum X17':'maximum',
	#'Zombie':'',
	#'Lich':'',
	#'FARTCLUBBER':'',
	'n95 Masque':'masque',
	'Shidding':'bangbangdoof',
	'El Beamo Laserino':'liberty',
	'Beam Me Up.':'aiden',
	'Subdue':'mallice',
	'Invazion':'mad villain',
	'Proud Pupper':'liberty',
	'Explode':'dogger',
	'El perrito Caliente':'*',
	'Liver Lips':'haunt',
	'o-o':'womb',
	'Lil Smokey':'',
	#'Blizzard':'',
	'B-D':'',
	'fruitcake':'',
	'Crisis Actress':'seagate',
	'Gotehreginson':'',
	'Franklin S. Tower':'blue jay',
	'some taco':'mjb',
	'Seealit':'seagate',
	'Freezin Nibblets':'amra',
	'doctor f':'',
	'MeIIax':'mallex',
	'CryRy':'ryry',
	'H-Dogger':'dogger',
	'DrowRanger':'maverick',
	'Hunter 20XX':'',
	'Orbitals':'barrier',
	'Turon':'',
	'NoGracias':'',
	'Brazzers':'',
	'mogystick':'mogy',
	'Tree 0f Life':'rick james',
	'Mood Swings':'hot heals',
	'Incentro':'diotrophes',
	'Maverick X':'maverick',
	'Nakoma':'tanzie',
	'MaIIex':'mallex',
	'Do Unto Others':'',
	'ItBurns':'burns',
	'Teething Problems':'barrier',
	'Rhombus':'*',
	'Meadowphysics':'barrier',
	'Calamari Safari':'macskull',
	'Hawt Heals':'hot heals',
	'Veggie Dogger':'dogger',
	'Barrier4Mod 2020':'barrier',
	'I Crit My Pants':'burns',
	'Salty AF':'masque',
	'av?1':'avprince',
	'PainFully':'seductive',
	'Ripples':'barrier',
	'ghostmaster1':'xhiggy',
	'AyNus':'',
	'Rigamortus':'ricko',
	'Taipan-':'maximum',
	'Scissor Rose':'',
	'sexiwhiteboi2003':'silit',
	'Hail Paimon':'z',
	'Bobcat Goldthwait':'',
	'Hand Banana':'',
	'Shifgrethor':'silent method',
	'Bulge SIider Maximum':'womb',
	'el Perrito Caliente':'*',
	'Ma. Rch':'march',
	'plantguy529':'silit',
	'Mallefficacy':'mallex',
	'Bear Force One':'hp',
	'Fyruminom':'numi',
	'paste':'xhiggy',
	'Treyy':'trey',
	'Esau':'blue jay',
	'Mbwun':'',
	'Dimension Shift':'',
	'Wingardium Leviosa':'',
	'Daniel hates humans':'masque',
	'OrbitaI':'vertigo blue',
	'thot crawler':'smallz',
	'Bennu':'',
	'Ajackalit':'',
	'lalalalalalala':'',
	'glhf':'ricko',
	'i saw Mez vent':'',
	'Pizza Pie':'',
	'Jackbox?':'',
	'adhesivewalrus67':'silit',
	'Tsundra':'sarr',
	'Architect Ticket Technician':'',
	'Raver':'',
	'Freedom Corp Raver':'',
	'Dancer':'',
	'Isaac the Bartender':'',
	'Null the Gull':'',
	'Hero Elevator Guard':'',
	'shock advised':'haunt',
	'hot dawger':'hot heals',
	'Frank':'',
	'Alimony':'hot heals',
	'Commando':'',
	'King Kunta':'',
	'light8ing':'haunt',
	'Little Pupper':'',
	'Sleet':'',
	'Envious':'syn',
	'IoVoI':'womb',
	'Wrecknut':'wreck',
	'Firenut':'',
	'GfNutGf':'paul',
	'Wreckk':'wreck',
	'BNotA':'',
	'RatNotRat':'paul',
	'Chika ChikaMeow Meow':'',
	'Burnn Sensation':'',
	'poneds onlyfans':'',
	'Intoxication':'',
	'Generic413922':'',
	'Marchicus':'march',
	'Noita':'',
	'o Y o':'womb',
	'Teensiest Dragon':'tempty',
	'Chloranthy':'',
	'Vengeful Spirit':'maverick',
	'some vegetable':'mjb',
	'Ghost Stories':'',
	'Cant Stop':'',
	'Sarsaparilla Gorilla':'macskull',
	'Phrasing AF':'',
	'Post Modern Sleaze':'',
	'Leftists Tears':'',
	'Miaou':'bang',
	'Overdose':'hp',
	'Galaxy Bowl':'bang',
	'Bi Fang':'',
	'Ricko':'ricko',
	'Feng Huang':'phoenix',
	'Doomspark':'mad villain',
	'NotPaul':'',
	'Kenberus':'kencian',
	'r1cK dAvi3s':'mad villain',
	'Wrecktumn':'wreck',
	'DoubleBurtJr':'doubleburt',
	'Implied Consent':'',
	'Relmu':'relmu',
	'Insanitary':'',
	'Outlawger':'bangbangdoof',
	'Los Avenidas':'cubano',
	'Prideful':'',
	'Imp':'',
	'Dark-Humor':'dark humor',
	'whatwhat in the butt':'',
	'Demetrious':'',
	'Shane Cooper':'',
	'Tristearin':'',
	'Lady Wreck':'',
	'Salient':'',
	'Baloney Man':'',
	'some cuddles':'mjb',
	'-Venomous':'freezerburn',
	'Gumballhead':'',
	'Misbeameanor':'',
	'Fushido Bushido':'',
	'Cannibus Leaf':'',
	'Harvey Danger':'deadly',
	'Brother Esau':'blue jay',
	'Plagiarism':'hot heals',
	'Raaaddd Maaann':'',
	'Gravitic Kara':'kara',
	'Lady Wicked':'',
	'Jim Beam':'deadly',
	'Thats SO Raven':'kyle',
	'Maximum X':'maximum',
	'Oppsy':'',
	'Ryval':'ryry',
	'tea sis?':'',
	'ima nice guy':'',
	'Sketchy AF':'masque',
	'Tanzie':'tanzie',
	'Oti Booti':'trey',
	'Sipherno':'siph',
	'PNP':'paul',
	'Maximum Dogger':'dogger',
	'WAP':'',
	'Temptys TrashPanda':'masque',
	'0 Y 0':'womb',
	'Jaws of Life':'rick james',
	'Stats Parser':'',
	'Vasectomy':'hot heals',
	'Phoenix Arrow':'',
	'High AF':'',
	'Alpha AFire':'',
	'Son of Mogh':'',
	'Spon':'bangbangdoof',
	'Trend':'hp',
	'Love Doctor':'hells',
	'Poned Lite':'poned',
	'angah bangah':'',
	'CiroHFan1':'ciro',
	'This On3':'',
	'GatherAtSpawn':'',
	'Sound Technician':'',
	'War Witch':'',
	'Planned Attack':'',
	'Pluto':'',
	'GetUp':'',
	'Social Media':'hot heals',
	'Ghostin':'poned',
	'Come Hitherism':'',
	'Fatez':'fatez',
	'Birthday Suit':'',
	'BdayNotBday':'paul',
	'dragged':'',
	'NotNot':'',
	'Sure Bet':'bangbangdoof',
	'VomIT Ray':'',
	'Kencianator':'kencian',
	'Eccojams':'m3z',
	'Circumstance':'',
	'New Kid':'',
	'Half Chub':'',
	'Mu Adept':'',
	'Punsie McKale':'',
	'Slanted Square':'',
	'but fucca':'',
	'Santa Lucia':'',
	'futtbucker':'',
	'buckfutter':'',
	'Mimetic Drift':'',
	'Heaven Scent':'',
	'Wintr':'',
	'Viral Telepathy':'',
	'False Vacuum':'',
	'Sigil Marcus':'',
	'Bequeathed':'',
	'Poppycock':'kyle',
	'Santa Sativa':'',
	'Emotional Wreck':'wreck',
	'Down Doggerr':'dogger',
	'I Have A Beam':'poned',
	'No Probllama':'womb',
	'Le Stranger':'',
	'TemptyGaveTrumpCovid':'',
	'Frigid Beaver':'',
	'ITS MILLER TIME':'',
	'Prayers4Tempty':'',
	'Grand Central':'',
	'I Said Biiiiish':'',
	'Lestranger Danger':'lestrange',
	'Syuzyaku':'',
	'M3zs Pointy Finger':'',
	'Cosine':'cosine',
	'DonrFarmMe':'',
	'Jaunt':'',
	'Pspsps':'',
	'Chewing AF':'',
	'Kirby AF':'',
	'.wmb':'womb',
	'some god':'mjb',
	'.Ziva':'',
	'Skin Tag':'womb',
	'Endorphanage':'',
	'Cubano 2024':'',
	'Solaire':'',
	'City of Angels':'',
	'Dai Li':'mallex',
	'some procs':'mjb',
	'RylyNotGood':'ryry',
	'CR Mochi':'',
	'Exiled Princess1':'exiled',
	'Refried Beam':'',
	'War Dynamics':'m3z',
	'Martian Max':'maximum',
	'Madvillainy':'mad villain',
	'Roguewash':'silit',
	'Suicidal':'hot heals',
	'warm':'xhiggy',
	'Pee Pee Poo Poo':'',
	'PeanutNotPeanut':'',
	'Nerf Herder':'',
	'ChikaChikaMeow Meow':'',
	'Disrespectful':'',
	'erkay':'',
	'Runner up Syn':'',
	'Lackluster Lobster':'larry lobster',
	'Male-Lex':'mallex',
	'some gymnast':'mjb',
	'Original Syn':'syn',
	'Lightning Car':'',
	'smol goat':'mjb',
	'Coprophagia':'',
	'Stellarator':'xhiggy',
	'Whoreo Beam Pie':'',
	'th0tful':'smallz',
	'Rowdy999':'rowdy',
	'Deciduous':'',
	'Tony Romo':'',
	'Hot Heals':'hot heals',
	'John BIaze':'haunt',
	'Chika Chik.a':'',
	'Tiddy Residue':'',
	'Cover Girl':'',
	'P O N E D':'poned',
	'STOP THE BLEEDING':'',
	'Bad Publicity':'hot heals',
	'New Name AF':'',
	'NotEvenWindowedMode':'',
	'Soila':'',
	'Wynell':'',
	'Tonks':'lestrange',
	'BizarresCookies':'',
	'Obnoxious AF':'masque',
	'Can I Be Frank?':'',
	'S3duct1v3':'seductive',
	'Black Tourmaline':'',
	'Scratch N SniffMehhh':'',
	'Nyx Goddess of Night':'',
	'Rumor':'void',
	'Triple Beam Dream':'',
	'Murder Inc':'',
	'Messe Kyrie':'bangbangdoof',
	'Reformed Poned':'poned',
	'Moontower':'tempty',
	'877-CASHNOW':'',
	'Abandonment Issues':'',
	'Counting Creys':'',
	'Judecca':'',
	'Colour Out of Space':'',
	'Janie is Toxic AF':'janie',
	'Maximum Despair-':'maximum',
	'Banana Hammock':'',
	'BarCoder':'',
	'RudeAsShet':'',
	'UnderTheButtNutHut':'',
	'TemptysNumbThroat':'',
	'Cosplays':'',
	'Energy Reserve 2.0':'',
	'Forestfyre':'',
	'Radio Panic':'',
	'Fishface S Tower':'blue jay',
	'el perrito caliente':'*',
	'March Reborn':'march',
	'perrito caliente':'*',
	'Basic Heal':'',
	'Blaziernoed1':'xhiggy',
	'dragonzoid1':'xhiggy',
	'SPANK EM':'',
	'Fractoring':'',
	'FireNotFire':'',
	'Firery Babe':'',
	'DowntownSugarCookie':'',
	'lastrongae':'lestrange',
	'HailQueenTempty':'',
	'woom':'womb',
	'thiccboi88':'',
	'Delightful':'liberty',
	'after th0t':'',
	'Maximum Justice':'maximum',
	'Shampoo':'hp',
	'Maxima Seguridad':'maximum',
}

if __name__ == "__main__":
    main()