plist = [

# fire
'BLAZE_ATTACK.FX',
'FIREBALL.FX',
'BLAZINGBOLT_ATTACK.FX',
'/INFERNOBOLT.FX',

# ice
'BITTERFREEZERAY.FX',
'BITTERICEBOLT.FX',
'BITTERFREEZEBOLT.FX',
'ICEBLAST.FX',

# BEAMRIFLE_DISINTEGRATE
'BEAMRIFLE_DISINTEGRATE.FX',
'BEAMRIFLE_CHARGEDSHOT.FX',
'BEAMRIFLE_LANCERSHOT.FX',

# emp
'HEALINGHANDS.FX',
'ABSORBPAIN.FX',
'STRENGTHHANDS2.FX',
'EMPATHY/RADIATIONEMISSION.FX',
'MINDWALL.FX',
'ENDURANCE.FX',
'FORTITUDE.FX',
'EMPATHYCUREWOUNDS.FX',

# pain
'SOOTH_ATTACK.FX',
'SHAREPAIN_ATTACK.FX',

# psn
'/POISONLIQUIDPROJECTILE.FX',
'/PALMPOISONLIQUIDPROJECTILE.FX',


# ill
'ILLUSDECOY.FX',
'ILLUSIONCONTROL/ILLUSBLIND.FX',

# plant
'THORNS/BUILDUP_ATTACK.FX',
'PLANTCONTROL/PLANTCONTROLHIT.FX',

# elec
'REJUVENATINGCIRCUITATK.FX',
'EMPOWERINGCIRCUITATK.FX',
'INSULATINGCIRCUITATK.FX',
'AMPUPATTACK.FX',

#nature
'CORROSIVESAP.FX',

# misc
'JAUNT_ATTACK.FX',
'MENTALPOWERS/COMMAND2.FX',
'MINDCONTROL/COMMAND2.FX',
'ALIGNMENT_JUSTICE.FX',
'AIM.FX',
'AIM_ACTIVATION.FX',
'SPIRITWARD.FX',
'SPIRTSHARKJAWS_CONDITIONAL.FX',
'/SCHOOLOFSHARKS_HIT.FX',
'FOSSILIZEHANDS.FX',
'/HIBERNATE.FX',
'/HIBERNATE_CONTINUING.FX',
'FIRECONTROL/SOOT.FX',
'/EMBERSHITSOOTANDCINDERS.FX',
'FLIGHT/NONCOMBATFLIGHT_NOFX.FX',
'MYSTICFLIGHT.FX',
'V_MAKO_SPIRITSHARK_CIRCLE_HIT',
'/INVISPHASE_FASTCAST.FX',
# 'WEAPONS/LASER_PISTOL_1.FX',
'FOLLOWUPHIT4.FX',
'/SKYRAIDERJETS.FX',
'PHASESHIFT_ATTACK.FX',
]


pdict = {
'BLAZE_ATTACK.FX':'blaze',
'FIREBALL.FX':'blaze',
'/INFERNOBOLT.FX':'blazing bolt',
'BLAZINGBOLT_ATTACK.FX':'blazing bolt',
'HEALINGHANDS.FX':'heal other',
'ABSORBPAIN.FX':'absorb pain',
'/POISONLIQUIDPROJECTILE.FX':'envenom',
'JAUNT_ATTACK.FX':'jaunt',
'MINDWALL.FX':'clear mind',
'EMPATHY/RADIATIONEMISSION.FX':'heal aura',
'REJUVENATINGCIRCUITATK.FX':'rejuv circuit',
'EMPOWERINGCIRCUITATK.FX':'emp circuit',
'MENTALPOWERS/COMMAND2.FX':'dominate',
'/PALMPOISONLIQUIDPROJECTILE.FX':'weaken',
'ENDURANCE.FX':'adreneline boost',
'FORTITUDE.FX':'fort',
'ALIGNMENT_JUSTICE.FX':'call to justice',
'ILLUSIONCONTROL/ILLUSBLIND.FX':'blind',
'THORNS/BUILDUP_ATTACK.FX':'toxins',
'ILLUSDECOY.FX':'phantom army',
'AIM.FX':'aim',
'AIM_ACTIVATION.FX':'aim',
'SPIRITWARD.FX':'spirit ward',
'AMPUPATTACK.FX':'amp up',
'INSULATINGCIRCUITATK.FX':'insulating circuit',
'SPIRTSHARKJAWS_CONDITIONAL.FX':'ssj',
'V_MAKO_SPIRITSHARK_CIRCLE_HIT':'ssj',
'/SCHOOLOFSHARKS_HIT.FX':'ssj',
'V_MAKO_SPIRITSHARK_FRENZY_BIGHOLD.FX':'ssj',
'BITTERFREEZEBOLT.FX':'bfr',
'BITTERICEBOLT.FX':'bfr',
'BITTERFREEZERAY.FX':'bib',
'ICEBLAST.FX':'ice blast',
'BEAMRIFLE_DISINTEGRATE.FX':'disintegrate',
'BEAMRIFLE_CHARGEDSHOT.FX':'penetrating ray/charged shot',
'BEAMRIFLE_LANCERSHOT.FX':'lancer',
'EMPATHYCUREWOUNDS.FX':'regen aura',
'FOSSILIZEHANDS.FX':'fossilize',
'/HIBERNATE.FX':'hibernate',
'/HIBERNATE_CONTINUING.FX':'hibernate',
'PLANTCONTROL/PLANTCONTROLHIT.FX':'strangler',
'CORROSIVESAP.FX':'corrosive enzyme',
'SOOTH_ATTACK.FX':'soothe',
'SHAREPAIN_ATTACK.FX':'share pain',
'FIRECONTROL/SOOT.FX':'char',
'FLIGHT/NONCOMBATFLIGHT_NOFX.FX':'mystic/flight',
'MYSTICFLIGHT.FX':'mystic/flight',
'/INVISPHASE_FASTCAST.FX':'phase',
# 'WEAPONS/LASER_PISTOL_1.FX':'crey',
'FOLLOWUPHIT4.FX':'fiery embrace',
'/EMBERSHITSOOTANDCINDERS.FX':'char',
'/SKYRAIDERJETS.FX':'raptor pack',
'PHASESHIFT_ATTACK.FX':'phase',
'MINDCONTROL/COMMAND2.FX':'dominate',
}

preverse = [
'ENDURANCE.FX',
'MINDWALL.FX',
'FORTITUDE.FX',
'PLANTCONTROL/PLANTCONTROLHIT.FX',
'V_MAKO_SPIRITSHARK_CIRCLE_HIT',
'/SCHOOLOFSHARKS_HIT.FX',
]

pemp = [
'HEALINGHANDS.FX',
'ABSORBPAIN.FX',
'STRENGTHHANDS2.FX',
]

name_filter  = [
'Mu Guardian',
'Phantasm',
'Decoy Phantasm',
'Decoy',
'Coralax Blue Hybrid',
'Dr',
'Poison Trap',
'Animated Stone',
'Superior Vigilant Assault',
'Blind',
'Galvanic Sentinel',
'Voltaic Geyser',
'Voltaic Sentinel',
'Water Spout',
'Fortunata Mistress',
'Superior Scourging Blast',
'German Shepherd',
'Ice Storm',
'Energy Font',
'Spectral Terror',

]