plist = [

# fire
'BLAZE_ATTACK.FX',
'FIREBALL.FX',
'BLAZINGBOLT_ATTACK.FX',

# ice
'ICEBLAST/BITTERFREEZERAY.FX',
'BITTERICEBOLT.FX',
'COLDCONTROL/BITTERFREEZERAY.FX',
'ICEBLAST.FX',

# beam
'BEAMRIFLE_DISINTEGRATE.FX',
'BEAMRIFLE_CHARGEDSHOT.FX',
'BEAMRIFLE_LANCERSHOT.FX',

# emp
'HEALINGHANDS.FX',
'ABSORBPAIN.FX',
'STRENGTHHANDS2.FX',
'EMPATHY/RADIATIONEMISSION.FX',
'MINDWALL.FX',
'ENDURANCE.FX',
'FORTITUDE.FX',
'EMPATHYCUREWOUNDS.FX',

# pain
'SOOTH_ATTACK.FX',
'SHAREPAIN_ATTACK.FX',

# psn
'POISONLIQUIDPROJECTILE.FX',
'PALMPOISONLIQUIDPROJECTILE.FX',


# ill
'ILLUSDECOY.FX',
#'ILLUSBLIND.FX',

# plant
'THORNS/BUILDUP_ATTACK.FX',
'PLANTCONTROL/PLANTCONTROLHIT.FX',

# elec
'REJUVENATINGCIRCUITATK.FX',
'EMPOWERINGCIRCUITATK.FX',
'INSULATINGCIRCUITATK.FX',
'AMPUPATTACK.FX',

#nature
'CORROSIVESAP.FX',

# misc
'JAUNT_ATTACK.FX',
'MENTALPOWERS/COMMAND2.FX',
'ALIGNMENT_JUSTICE.FX',
'AIM.FX',
'AIM_ACTIVATION.FX',
'SPIRITWARD.FX',
'SPIRTSHARKJAWS_CONDITIONAL.FX',
'FOSSILIZEHANDS.FX 0',
'HIBERNATE_CONTINUING.FX',

]


pdict = {
'BLAZE_ATTACK.FX':'blaze',
'FIREBALL.FX':'blaze',
'HEALINGHANDS.FX':'heal other',
'ABSORBPAIN.FX':'absorb pain',
'POISONLIQUIDPROJECTILE.FX':'envenom',
'BLAZINGBOLT_ATTACK.FX':'blazing bolt',
'JAUNT_ATTACK.FX':'jaunt',
'MINDWALL.FX':'clear mind',
'EMPATHY/RADIATIONEMISSION.FX':'heal aura',
'REJUVENATINGCIRCUITATK.FX':'rejuv circuit',
'EMPOWERINGCIRCUITATK.FX':'emp circuit',
'MENTALPOWERS/COMMAND2.FX':'dominate',
'PALMPOISONLIQUIDPROJECTILE.FX':'weaken',
'ENDURANCE.FX':'adreneline boost',
'FORTITUDE.FX':'fort',
'ALIGNMENT_JUSTICE.FX':'call to justice',
#'ILLUSBLIND.FX':'blind',
'THORNS/BUILDUP_ATTACK.FX':'toxins',
'ILLUSDECOY.FX':'phantom army',
'AIM.FX':'aim',
'AIM_ACTIVATION.FX':'aim',
'SPIRITWARD.FX':'aim',
'AMPUPATTACK.FX':'amp up',
'INSULATINGCIRCUITATK.FX':'insulating circuit',
'SPIRTSHARKJAWS_CONDITIONAL.FX':'ssj',
'ICEBLAST/BITTERFREEZERAY.FX':'bib', # ??
'BITTERFREEZEBOLT.FX':'bfr',
'COLDCONTROL/BITTERFREEZERAY.FX':'bib',
'ICEBLAST.FX':'ice blast',
'BEAMRIFLE_DISINTEGRATE.FX':'disintegrate',
'BEAMRIFLE_CHARGEDSHOT.FX':'penetrating ray/charged shot',
'BEAMRIFLE_LANCERSHOT.FX':'lancer',
'EMPATHYCUREWOUNDS.FX':'regen aura',
'FOSSILIZEHANDS.FX':'fossilize',
'HIBERNATE_CONTINUING.FX':'hibernate',
'PLANTCONTROL/PLANTCONTROLHIT.FX':'strangler',
'CORROSIVESAP.FX':'corrosive enzyme',
'SOOTH_ATTACK.FX':'soothe',
'SHAREPAIN_ATTACK.FX':'share pain',
}

preverse = [
'ENDURANCE.FX',
'MINDWALL.FX',
'FORTITUDE.FX',
'PLANTCONTROL/PLANTCONTROLHIT.FX',
]

pemp = [
'HEALINGHANDS.FX',
'ABSORBPAIN.FX',
'STRENGTHHANDS2.FX',
]

name_filter  = [
'Mu Guardian',
'Phantasm',
'Decoy Phantasm',
'Decoy',
'Coralax Blue Hybrid',
'Dr',
'Poison Trap',
'Animated Stone',
'Superior Vigilant Assault',
'Blind',
'Galvanic Sentinel',
'Voltaic Geyser',
'Voltaic Sentinel',
'Water Spout',
'Fortunata Mistress',
'Superior Scourging Blast',
'German Shepherd',

]